package com.appbana.service;

import com.appbana.JdbcManager;
import com.appbana.SchemaManager;
import com.appbana.model.EntitySchema;
import com.appbana.model.TenantContext;
import org.junit.jupiter.api.*;

import java.sql.Connection;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.*;

import static org.junit.jupiter.api.Assertions.*;

/**
 * Test suite for EntityCrudService with TenantContext support
 * 
 * Tests both context-aware (multi-tenant) and legacy (backward compatible)
 * methods
 */
@TestInstance(TestInstance.Lifecycle.PER_CLASS)
public class EntityCrudServiceTest {

    private EntityCrudService service;
    private EntitySchema testSchema;
    private TenantContext tenant1AppA;
    private TenantContext tenant1AppB;
    private TenantContext tenant2AppA;

    @BeforeAll
    void setupDatabase() throws SQLException {
        service = new EntityCrudService();

        // Create contexts
        tenant1AppA = new TenantContext("tenant-1", "app-a");
        tenant1AppB = new TenantContext("tenant-1", "app-b");
        tenant2AppA = new TenantContext("tenant-2", "app-a");

        // Create base test schema definition
        testSchema = new EntitySchema();
        testSchema.setName("test_users");
        testSchema.setDatasourceName(null); // default H2

        List<EntitySchema.Field> fields = new ArrayList<>();

        // Primary key
        EntitySchema.Field id = new EntitySchema.Field();
        id.setName("id");
        id.setType("long");
        id.setPrimaryKey(true);
        id.setAutoIncrement(true);
        fields.add(id);

        // Data fields
        EntitySchema.Field name = new EntitySchema.Field();
        name.setName("name");
        name.setType("string");
        name.setLength(100);
        name.setRequired(true);
        fields.add(name);

        EntitySchema.Field email = new EntitySchema.Field();
        email.setName("email");
        email.setType("string");
        email.setLength(100);
        fields.add(email);

        EntitySchema.Field age = new EntitySchema.Field();
        age.setName("age");
        age.setType("int");
        fields.add(age);

        testSchema.setFields(fields);

        // Create legacy table manually (for backward compatibility tests)
        try (Connection conn = JdbcManager.getConnection(null);
                Statement stmt = conn.createStatement()) {
            stmt.execute("DROP TABLE IF EXISTS \"TEST_USERS\"");
            stmt.execute("""
                        CREATE TABLE "TEST_USERS" (
                            "ID" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                            "NAME" VARCHAR(100) NOT NULL,
                            "EMAIL" VARCHAR(100),
                            "AGE" INT
                        )
                    """);
        }

        // Create physical tables for isolation tests
        // We use SchemaManager to ensure the table names match exactly what the service
        // expects
        SchemaManager.saveSchema(scopedSchema(tenant1AppA));
        SchemaManager.saveSchema(scopedSchema(tenant1AppB));
        SchemaManager.saveSchema(scopedSchema(tenant2AppA));
    }

    @AfterEach
    void cleanupData() throws SQLException {
        // Clean legacy table
        try (Connection conn = JdbcManager.getConnection(null);
                Statement stmt = conn.createStatement()) {
            stmt.execute("DELETE FROM \"TEST_USERS\"");
        }

        // Clean isolated tables
        cleanTable(tenant1AppA);
        cleanTable(tenant1AppB);
        cleanTable(tenant2AppA);
    }

    private void cleanTable(TenantContext context) throws SQLException {
        EntitySchema schema = scopedSchema(context);
        String tableName = SchemaManager.getPhysicalTableName(schema);
        try (Connection conn = JdbcManager.getConnection(null);
                Statement stmt = conn.createStatement()) {
            // Quote table name to handle mixed case/special chars correctly if needed,
            // though getPhysicalTableName usually handles it or returns simple string.
            // SchemaManager.getPhysicalTableName returns unquoted string usually.
            stmt.execute("DELETE FROM \"" + tableName.toUpperCase() + "\"");
        }
    }

    @AfterAll
    void teardownDatabase() throws SQLException {
        try (Connection conn = JdbcManager.getConnection(null);
                Statement stmt = conn.createStatement()) {
            stmt.execute("DROP TABLE IF EXISTS \"TEST_USERS\"");

            // Drop isolated tables
            stmt.execute("DROP TABLE IF EXISTS \""
                    + SchemaManager.getPhysicalTableName(scopedSchema(tenant1AppA)).toUpperCase() + "\"");
            stmt.execute("DROP TABLE IF EXISTS \""
                    + SchemaManager.getPhysicalTableName(scopedSchema(tenant1AppB)).toUpperCase() + "\"");
            stmt.execute("DROP TABLE IF EXISTS \""
                    + SchemaManager.getPhysicalTableName(scopedSchema(tenant2AppA)).toUpperCase() + "\"");
        }
    }

    // Helper to create a context-specific schema clone
    private EntitySchema scopedSchema(TenantContext ctx) {
        EntitySchema s = new EntitySchema();
        s.setName(testSchema.getName());
        s.setDatasourceName(testSchema.getDatasourceName());
        s.setTenantId(ctx.getTenantId());
        s.setAppId(ctx.getAppId());
        // Shallow copy fields is fine as they are not modified
        s.setFields(new ArrayList<>(testSchema.getFields()));
        return s;
    }

    // ==================== Context-Aware Insert Tests ====================

    @Test
    @DisplayName("Should insert record with tenant/app context")
    void testInsertWithContext() throws SQLException {
        Map<String, Object> data = new HashMap<>();
        data.put("name", "Alice");
        data.put("email", "alice@example.com");
        data.put("age", 30);

        Object id = service.insertRecord(tenant1AppA, scopedSchema(tenant1AppA), data);

        assertNotNull(id);
        assertTrue(id instanceof Long || id instanceof Integer);
    }

    @Test
    @DisplayName("Should auto-inject tenant_id and app_id on insert")
    void testAutoInjectTenantAndApp() throws SQLException {
        // With physical isolation, we don't inject tenant_id/app_id columns.
        // But we verify that the data is retrievable from the correct context.
        Map<String, Object> data = new HashMap<>();
        data.put("name", "Bob");
        data.put("email", "bob@example.com");

        Object id = service.insertRecord(tenant1AppA, scopedSchema(tenant1AppA), data);

        // Verify data was inserted
        Map<String, Object> retrieved = service.getById(tenant1AppA, scopedSchema(tenant1AppA), id.toString());
        assertNotNull(retrieved);
        assertEquals("Bob", retrieved.get("NAME"));
    }

    @Test
    @DisplayName("Should throw exception when context is null on insert")
    void testInsertRequiresContext() {
        Map<String, Object> data = new HashMap<>();
        data.put("name", "Charlie");

        IllegalArgumentException exception = assertThrows(
                IllegalArgumentException.class,
                // We pass testSchema (no context) but null TenantContext arg
                () -> service.insertRecord(null, testSchema, data));

        assertTrue(exception.getMessage().contains("TenantContext is required"));
    }

    // ==================== Context-Aware List Tests ====================

    @Test
    @DisplayName("Should list only records for specific tenant/app")
    void testListAllWithIsolation() throws SQLException {
        // Insert records for different tenants/apps
        insertRecord(tenant1AppA, "Alice");
        insertRecord(tenant1AppA, "Bob");
        insertRecord(tenant1AppB, "Charlie");
        insertRecord(tenant2AppA, "David");

        // List for tenant1/app-a
        List<Map<String, Object>> tenant1AppARecords = service.listAll(tenant1AppA, scopedSchema(tenant1AppA));
        assertEquals(2, tenant1AppARecords.size());
        Set<String> names1A = extractNames(tenant1AppARecords);
        assertTrue(names1A.contains("Alice"));
        assertTrue(names1A.contains("Bob"));

        // List for tenant1/app-b
        List<Map<String, Object>> tenant1AppBRecords = service.listAll(tenant1AppB, scopedSchema(tenant1AppB));
        assertEquals(1, tenant1AppBRecords.size());
        assertEquals("Charlie", tenant1AppBRecords.get(0).get("NAME"));

        // List for tenant2/app-a
        List<Map<String, Object>> tenant2AppARecords = service.listAll(tenant2AppA, scopedSchema(tenant2AppA));
        assertEquals(1, tenant2AppARecords.size());
        assertEquals("David", tenant2AppARecords.get(0).get("NAME"));
    }

    @Test
    @DisplayName("Should throw exception when context is null on list")
    void testListRequiresContext() {
        assertThrows(
                IllegalArgumentException.class,
                () -> service.listAll(null, testSchema));
    }

    // ==================== Context-Aware GetById Tests ====================

    @Test
    @DisplayName("Should get record by ID within tenant/app scope")
    void testGetByIdWithIsolation() throws SQLException {
        // Insert records in different contexts
        Object id1 = insertRecord(tenant1AppA, "Alice");
        Object id2 = insertRecord(tenant1AppB, "Bob");

        // Get from correct context
        Map<String, Object> alice = service.getById(tenant1AppA, scopedSchema(tenant1AppA), id1.toString());
        assertNotNull(alice);
        assertEquals("Alice", alice.get("NAME"));

        // Try to get from wrong context (should return null - isolation)
        // Note: With physical isolation, the ID likely won't even exist in the other
        // table, or if it does, it's a different record.
        // Here we query table B for ID from table A. It should be null.
        Map<String, Object> wrongContext = service.getById(tenant1AppB, scopedSchema(tenant1AppB), id1.toString());
        assertNull(wrongContext, "Should not retrieve record from different app context");
    }

    @Test
    @DisplayName("Should return null when record doesn't exist in context")
    void testGetByIdNotFound() throws SQLException {
        Map<String, Object> result = service.getById(tenant1AppA, scopedSchema(tenant1AppA), "99999");
        assertNull(result);
    }

    // ==================== Context-Aware Update Tests ====================

    @Test
    @DisplayName("Should update record within tenant/app scope")
    void testUpdateByIdWithIsolation() throws SQLException {
        // Insert record
        Object id = insertRecord(tenant1AppA, "Alice");

        // Update record
        Map<String, Object> updates = new HashMap<>();
        updates.put("name", "Alice Updated");
        updates.put("age", 31);

        int rowsUpdated = service.updateById(tenant1AppA, scopedSchema(tenant1AppA), id.toString(), updates);
        assertEquals(1, rowsUpdated);

        // Verify update
        Map<String, Object> updated = service.getById(tenant1AppA, scopedSchema(tenant1AppA), id.toString());
        assertEquals("Alice Updated", updated.get("NAME"));
        assertEquals(31, updated.get("AGE"));
    }

    @Test
    @DisplayName("Should not update record from different context")
    void testUpdateIsolation() throws SQLException {
        // Insert record in app-a
        Object id = insertRecord(tenant1AppA, "Alice");

        // Try to update from app-b (should fail - wrong context/table)
        Map<String, Object> updates = new HashMap<>();
        updates.put("name", "Alice Hacked");

        int rowsUpdated = service.updateById(tenant1AppB, scopedSchema(tenant1AppB), id.toString(), updates);
        assertEquals(0, rowsUpdated, "Should not update record from different context");

        // Verify original record unchanged
        Map<String, Object> original = service.getById(tenant1AppA, scopedSchema(tenant1AppA), id.toString());
        assertEquals("Alice", original.get("NAME"));
    }

    // Removed testCannotUpdateIsolationFields as those fields do not exist

    // ==================== Context-Aware Delete Tests ====================

    @Test
    @DisplayName("Should delete record within tenant/app scope")
    void testDeleteByIdWithIsolation() throws SQLException {
        // Insert record
        Object id = insertRecord(tenant1AppA, "Alice");

        // Delete record
        int rowsDeleted = service.deleteById(tenant1AppA, scopedSchema(tenant1AppA), id.toString());
        assertEquals(1, rowsDeleted);

        // Verify deleted
        Map<String, Object> deleted = service.getById(tenant1AppA, scopedSchema(tenant1AppA), id.toString());
        assertNull(deleted);
    }

    @Test
    @DisplayName("Should not delete record from different context")
    void testDeleteIsolation() throws SQLException {
        // Insert record in app-a
        Object id = insertRecord(tenant1AppA, "Alice");

        // Try to delete from app-b (should fail - wrong context)
        int rowsDeleted = service.deleteById(tenant1AppB, scopedSchema(tenant1AppB), id.toString());
        assertEquals(0, rowsDeleted, "Should not delete record from different context");

        // Verify record still exists
        Map<String, Object> record = service.getById(tenant1AppA, scopedSchema(tenant1AppA), id.toString());
        assertNotNull(record);
        assertEquals("Alice", record.get("NAME"));
    }

    // ==================== Backward Compatibility Tests ====================

    @Test
    @DisplayName("Should maintain backward compatibility for insertRecord without context")
    void testLegacyInsertStillWorks() throws SQLException {
        Map<String, Object> data = new HashMap<>();
        // Legacy insert does not check tenant_id/app_id in the service anymore if the
        // table doesn't have them
        // But we can check basic insertion
        data.put("name", "Legacy User");
        data.put("email", "legacy@example.com");

        Object id = service.insertRecord(testSchema, data);
        assertNotNull(id);
    }

    @Test
    @DisplayName("Should maintain backward compatibility for listAll without context")
    void testLegacyListStillWorks() throws SQLException {
        // Insert using legacy method
        Map<String, Object> data = new HashMap<>();
        data.put("name", "Legacy User");

        service.insertRecord(testSchema, data);

        // List using legacy method (returns all records without filtering)
        List<Map<String, Object>> all = service.listAll(testSchema);
        assertNotNull(all);
        assertTrue(all.size() >= 1);
    }

    // ==================== Helper Methods ====================

    private Object insertRecord(TenantContext context, String name) throws SQLException {
        Map<String, Object> data = new HashMap<>();
        data.put("name", name);
        data.put("email", name.toLowerCase() + "@example.com");
        return service.insertRecord(context, scopedSchema(context), data);
    }

    private Set<String> extractNames(List<Map<String, Object>> records) {
        Set<String> names = new HashSet<>();
        for (Map<String, Object> record : records) {
            names.add((String) record.get("NAME"));
        }
        return names;
    }
}
