/**
 * approval-columns.ts — Phase C3.1.
 *
 * The eight columns the backend injects into every approval-required entity
 * table. Kept in one place so the runtime agrees with
 * `GenericEntityRoutes.APPROVAL_FIELD_NAMES` on the Java side.
 *
 * Why the runtime needs this at all: pages are generated by `GeneratePageTool`
 * from the entity's *user-defined* fields, so `node.props.fields` never lists
 * the injected approval columns. Without special-casing, an approval-required
 * entity would render a table with no approval state visible at all.
 */

/** Every column the approval machinery injects. Lower-case, as the API returns. */
export const APPROVAL_COLUMNS = [
  'approval_status',
  'approval_revision',
  'approval_parent_id',
  'submitted_by',
  'submitted_at',
  'approved_by',
  'approved_at',
  'rejection_reason',
] as const;

export const APPROVAL_STATUS_COLUMN = 'approval_status';

const APPROVAL_COLUMN_SET: ReadonlySet<string> = new Set<string>(APPROVAL_COLUMNS);

/** True for any injected approval column, in any casing. */
export function isApprovalColumn(name: string): boolean {
  return APPROVAL_COLUMN_SET.has(name.toLowerCase());
}

/** True for the approval status column specifically, in any casing. */
export function isApprovalStatusColumn(name: string): boolean {
  return name.toLowerCase() === APPROVAL_STATUS_COLUMN;
}

/**
 * Reads a value from a row tolerating column-name casing.
 *
 * Necessary because the backend returns different casing depending on the
 * query path: `listAdvanced` aliases columns `AS "field"` and yields lower-case
 * keys, while a plain `SELECT *` over quoted upper-case identifiers yields
 * UPPER-case keys.
 */
export function readRowValue(row: Record<string, unknown> | null | undefined, column: string): unknown {
  if (!row) return undefined;
  if (column in row) return row[column];
  const lower = column.toLowerCase();
  for (const key of Object.keys(row)) {
    if (key.toLowerCase() === lower) return row[key];
  }
  return undefined;
}

/**
 * True when the rows returned by the API carry approval metadata — i.e. this
 * entity has the approval workflow enabled. Derived from the data rather than
 * from schema flags so it works for pages generated before approval was turned
 * on, and so it cannot drift from what the backend actually returns.
 */
export function rowsHaveApprovalColumns(rows: ReadonlyArray<Record<string, unknown>>): boolean {
  const first = rows[0];
  if (!first) return false;
  return Object.keys(first).some((k) => k.toLowerCase() === APPROVAL_STATUS_COLUMN);
}

/** Suffix appended to an entity name to key a level-2 checker queue entry. */
export const CHECKER_L2_SUFFIX = '::L2';

/**
 * Two-level checker chain — `checkerEntities`/`pendingCounts`/`queueEntity`
 * encode "this is the level-2 queue for X" as the plain string `"X::L2"`
 * rather than a richer shape, so every existing `string[]` /
 * `Record<string, number>` consumer keeps working unchanged. Callers that
 * care about the level (fetching, labelling, titling) parse it back out here.
 */
export interface ParsedCheckerEntityKey {
  /** The bare entity name, with any `::L2` suffix stripped. */
  readonly entityName: string;
  /** 1 for the standard queue, 2 for the level-2 (final signoff) queue. */
  readonly level: 1 | 2;
}

export function parseCheckerEntityKey(key: string): ParsedCheckerEntityKey {
  if (key.endsWith(CHECKER_L2_SUFFIX)) {
    return { entityName: key.slice(0, -CHECKER_L2_SUFFIX.length), level: 2 };
  }
  return { entityName: key, level: 1 };
}

