package com.appbana.config;

import java.util.ArrayList;
import java.util.List;

import lombok.Data;

@Data
public class AppConfig {
    private String jdbcUrl = "jdbc:h2:./data/appbana;AUTO_SERVER=TRUE";
    private String username = "sa";
    private String password = "";
    private String driver = "org.h2.Driver"; // optional override
    private String name = "default"; // datasource name

    // multi-datasource support
    private List<DatasourceConfig> datasources = new ArrayList<>();
    private String activeDatasource; // name

    // Optional token-based auth (if both null/blank, auth is disabled)
    private String adminToken; // full read-write access
    private String readToken; // read-only access

    // Optional HTTPS support
    private Boolean httpsEnabled; // if true, start an HTTPS server as configured
    private Integer httpsPort; // default 8443 if enabled and not set
    private String keystorePath; // path to JKS/PKCS12 keystore
    private String keystorePassword; // keystore password
    private String keyPassword; // key password (defaults to keystorePassword if null)
    private Boolean redirectHttpToHttps; // if true, HTTP server redirects all requests to HTTPS

    // Web server implementation: "jdk" (default) or "tomcat"
    private String serverType; // null => default to "jdk"

    // AI Provider Configuration
    private String aiProvider; // "openai", "anthropic", or "ollama"

    // OpenAI settings
    private String openaiApiKey; // API key (or use OPENAI_API_KEY env var)
    private String openaiModel = "gpt-4o-mini"; // default model

    // Anthropic settings
    private String anthropicApiKey; // API key (or use ANTHROPIC_API_KEY env var)
    private String anthropicModel = "claude-3-5-sonnet-20241022"; // default model

    // Ollama settings (local AI)
    private String ollamaUrl = "http://localhost:11434"; // Ollama server URL
    private String ollamaModel = "llama3.1"; // default model

    // Database migration settings
    private Boolean flywayCleanOnStart = false; // Set to true to clean DB on startup (DANGER: deletes all data!)

    // AI Configuration Getters/Setters
    // Note: Standard getters/setters generated by Lombok

    public String getOpenaiApiKey() {
        // Try config first, then environment variables (multiple naming variations)
        if (openaiApiKey != null)
            return openaiApiKey;

        // Check all possible environment variable names
        String envKey = System.getenv("OPEN_API_KEY"); // User's variable name
        if (envKey != null)
            return envKey.trim();

        envKey = System.getenv("OPEN_AI_KEY"); // Alternative
        if (envKey != null)
            return envKey.trim();

        String standardKey = System.getenv("OPENAI_API_KEY"); // Standard OpenAI convention
        if (standardKey != null)
            return standardKey.trim();

        return null;
    }

    public String getAnthropicApiKey() {
        // Try config first, then environment variable
        return anthropicApiKey != null ? anthropicApiKey : System.getenv("ANTHROPIC_API_KEY");
    }
}
